server:
  port: ${PORT:0}

spring:
  application:
    name: quiz-api
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USER}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: false
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  liquibase:
    enabled: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    change-log: classpath:db/changelog/changelog-master.xml

management:
  endpoint:
    shutdown:
      enabled: true

token:
  expiration: ${TOKEN_EXPIRATION}
  secret: ${TOKEN_SECRET}