spring:
  datasource:
    url: jdbc:h2:mem:quizTest
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  h2:
    console:
      enabled: true
      path: /h2
  cloud:
    config:
      enabled: false

token:
  expiration: 864000000
  secret: asdWasdWASGHEt31Sh34As5

logging:
  level:
    "[org.springframework.web]": ERROR
    "[com.martikan.quizapi]": DEBUG
    "[org.hibernate]": DEBUG